# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ANT+ build and deploy website

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Install Dependencies
    - name: Install Dependencies
      run: |
        dotnet restore AntPlus
        dotnet restore AntRadioInterface
        dotnet restore AntPlus.Extensions.Hosting
        dotnet restore AntPlus.UnitTests
        dotnet restore Examples/AntUsbStick
        dotnet restore Extensions/Hosting/Hosting.UnitTests
        dotnet restore Documentation/Documentation.shfbproj

    # Build solution in Github configuration
    - name: Build NuGet Packages
      run: dotnet build --no-restore --configuration Github

    # Build Documentation
    - name: Build Documentation
      run: dotnet build Documentation/Documentation.shfbproj --no-restore --configuration Release -p:AlwaysLoadProject=true
    - name: Setup Pages
      uses: actions/configure-pages@v5
    # Upload the site located in docs directory
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'

  deploy:
    needs: build

    # Grant permissions to deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write

    # Deploy to GitHub Pages environment
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deployment URL
      run: echo "Deployed to ${{ needs.build.steps.deployment.outputs.page_url }}"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4