# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Release to NuGet and Website

on:
  release:
    types:
      - published
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Restore Dependencies
    - name: Restore Dependencies
      run: |
        dotnet restore AntPlus
        dotnet restore AntRadioInterface
        dotnet restore AntPlus.Extensions.Hosting
        dotnet restore AntPlus.UnitTests
        dotnet restore Examples/AntUsbStick
        dotnet restore Extensions/Hosting/Hosting.UnitTests
        dotnet restore Documentation/Documentation.shfbproj

    # Build Github Solution Configuration
    - name: Build NuGet Packages
      run: dotnet build --no-restore --configuration Github

    # Run Unit Tests
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity minimal --configuration Github

    # Publish NuGet Packages
    - name: Publish NuGet Packages
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

    # Build Documentation and Upload Artifacts
    - name: Build Documentation
      run: dotnet build Documentation/Documentation.shfbproj --no-restore --configuration Release
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './Documentation/Help'

  deploy:
    needs: build

    # Grant permissions to deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write

    # Deploy to GitHub Pages environment
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    # Deploy Documentation to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
